# Generated by Django 5.0.6 on 2024-10-30 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'mathematics'), ('english', 'english'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('geography', 'geography'), ('further-mathematics', 'further-mathematics'), ('economics', 'economics'), ('agric', 'agric'), ('civic', 'civic'), ('marketing', 'marketing'), ('crs', 'crs'), ('government', 'government'), ('account', 'account'), ('commerce', 'commerce'), ('literature', 'literature'), ('yoruba', 'yoruba'), ('business-studies', 'business-studies'), ('basic-science', 'basic-science'), ('basic-technology', 'basic-technology'), ('p.h.e', 'p.h.e'), ('music', 'music'), ('french', 'french'), ('home-economics', 'home-economics'), ('c.c.a', 'c.c.a'), ('social-studies', 'social-studies'), ('security-education', 'security-education'), ('history', 'history')], max_length=200)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('dutarion', models.TimeField(blank=True, null=True)),
                ('clas', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('solution', models.TextField()),
                ('subject', models.CharField(choices=[('mathematics', 'mathematics'), ('english', 'english'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('geography', 'geography'), ('further-mathematics', 'further-mathematics'), ('economics', 'economics'), ('agric', 'agric'), ('civic', 'civic'), ('marketing', 'marketing'), ('crs', 'crs'), ('government', 'government'), ('account', 'account'), ('commerce', 'commerce'), ('literature', 'literature'), ('yoruba', 'yoruba'), ('business-studies', 'business-studies'), ('basic-science', 'basic-science'), ('basic-technology', 'basic-technology'), ('p.h.e', 'p.h.e'), ('music', 'music'), ('french', 'french'), ('home-economics', 'home-economics'), ('c.c.a', 'c.c.a'), ('social-studies', 'social-studies'), ('security-education', 'security-education'), ('history', 'history')], max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examapp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examapp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
