# Generated by Django 5.0.6 on 2024-10-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='dutarion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
