# Generated by Django 5.0.6 on 2024-10-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0002_alter_exam_dutarion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
