# Generated by Django 5.0.6 on 2024-11-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0007_remove_answer_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='quest',
        ),
    ]
