# Generated by Django 5.0.6 on 2024-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0010_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='dutarion',
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=120),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
