# Generated by Django 5.0.6 on 2024-11-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0011_remove_question_exam_remove_exam_dutarion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('solution', models.TextField()),
                ('subject', models.CharField(choices=[('mathematics', 'mathematics'), ('english', 'english'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('geography', 'geography'), ('further-mathematics', 'further-mathematics'), ('economics', 'economics'), ('agric', 'agric'), ('civic', 'civic'), ('marketing', 'marketing'), ('crs', 'crs'), ('government', 'government'), ('account', 'account'), ('commerce', 'commerce'), ('literature', 'literature'), ('yoruba', 'yoruba'), ('business-studies', 'business-studies'), ('basic-science', 'basic-science'), ('basic-technology', 'basic-technology'), ('p.h.e', 'p.h.e'), ('music', 'music'), ('french', 'french'), ('home-economics', 'home-economics'), ('c.c.a', 'c.c.a'), ('social-studies', 'social-studies'), ('security-education', 'security-education'), ('history', 'history')], max_length=1000000)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examapp.exam')),
            ],
        ),
    ]
