# Generated by Django 5.0.6 on 2024-11-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0013_exam_total_question_delete_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswers',
        ),
    ]
